name: Node CI

on:
  push:
    tags: v*

jobs:
  build:

    runs-on: [macos]

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build MacOS X package
        run: |
          npm install
          npm run dist
      - name: Git Release
        uses: anton-yurchenko/git-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: "false"
          PRE_RELEASE: "false"
          CHANGELOG_FILE: "CHANGELOG.md"
        with:
          args: |
            dist/Grace-*.dmg
